database:
  host: localhost
  port: 3306
  name: punishment
  username: user
  password: password

messages:
  playerAlreadyBlacklisted: "&cPlayer &7{player}&c is already blacklisted"
  playerNotOnline: "&cPlayer &7{player}&c is not online"
  playerNotBanned: "&cPlayer &7{player}&c is not banned"
  playerNotMuted: "&cPlayer &7{player}&c is not muted"
  playerNotBlacklisted: "&cPlayer &7{player}&c is not blacklisted"
  playerUnBlacklist: "&aPlayer &7{player}&a it was unblacklisted"
  playerUnBanned: "&aPlayer &7{player}&a it was unbanned"
  playerUnMuted: "&aPlayer &7{player}&a it was unmuted"
  muteResponse: "&dYou have been mutated for &7{reason} &d(&7{duration}&d)"

  confirmedBlacklist: "&aPlayer blacklisted successfully"
  confirmedBan: "&aPlayer banned successfully"
  confirmedMute: "&aPlayer muted successfully"
  banDisplay:
    - "&d&lOrbital&5&lStudios"
    - ""
    - "&dYou have been &lBanned"
    - "&dExpires: &7{expiration}"
    - "&dReason: &7{reason}"
  blacklistDisplay:
    - "&d&lOrbital&5&lStudios"
    - ""
    - "&dYou have been &lBLACKLISTED"
    - "&dReason: &7{reason}"