database:
  host: localhost
  port: 3306
  name: punishment
  username: user
  password: password

messages:
  playerNotOnline: "&cPlayer &7{player}&c is not online"
  playerNotBanned: "&cPlayer &7{player}&c is not banned"
  playerUnbanned: "&aPlayer &7{player}&a it was unbanned"
  confirmedBan: "&aPlayer banned successfully"
  banDisplay:
    - "&d&lOrbital&5&lStudios"
    - ""
    - "&dYou have been &lBanned"
    - "&dExpires: &7{expiration}"
    - "&dReason: &7{reason}"