database:
  host: localhost
  port: 3306
  name: punishment
  username: user
  password: password

messages:
  playerAlreadyBlacklisted: "&cPlayer &7{player}&c is already blacklisted"
  playerAlreadyMuted: "&cPlayer &7{player}&c is already muted"
  playerNotOnline: "&cPlayer &7{player}&c is not online"
  playerNotBanned: "&cPlayer &7{player}&c is not banned"
  playerNotMuted: "&cPlayer &7{player}&c is not muted"
  playerNotBlacklisted: "&cPlayer &7{player}&c is not blacklisted"
  playerUnBlacklist: "&aPlayer &7{player}&a it was unblacklisted"
  playerUnBanned: "&aPlayer &7{player}&a it was unbanned"
  playerUnMuted: "&aPlayer &7{player}&a it was unmuted"
  muteResponse: "&dYou have been mutated for &7{reason} &d(&7{duration}&d)"
  confirmedBlacklist: "&aPlayer blacklisted successfully"
  confirmedBan: "&aPlayer banned successfully"
  confirmedMute: "&aPlayer muted successfully"
  punishNotify:
    - " &5&m-------------------------------"
    - "&5  ● &dAction: &f{action}"
    - "&5  ● &dAction By: &f{staffer}"
    - "&5  ● &dSuffered by: &f{player}"
    - "&5  ● &dReason: &f{reason}"
    - "&5  ● &dDuration: &f{duration}"
    - " &5&m-------------------------------"
  unPunishNotify:
    - " &5&m-------------------------------"
    - "&5  ● &dAction: &f{action}"
    - "&5  ● &dAction By: &f{staffer}"
    - "&5  ● &dSuffered by: &f{player}"
    - "&5  ● &dReason: &f{reason}"
    - " &5&m-------------------------------"

  banDisplay:
    - "&d&lOrbital&5&lStudios"
    - ""
    - "&dYou have been &lBanned"
    - "&dExpires: &7{expiration}"
    - "&dReason: &7{reason}"
  blacklistDisplay:
    - "&d&lOrbital&5&lStudios"
    - ""
    - "&dYou have been &lBLACKLISTED"
    - "&dReason: &7{reason}"
  kickDisplay:
    - "&d&lOrbital&5&lStudios"
    - ""
    - "&dYou have been &lKicked"
    - "&dReason: &7{reason}"

gui:
  title: "§dPunish History"
  titleBook: "&dPunish"
  punishMaterial: BOOK
  materialPage: ARROW
  materialFill: GRAY_STAINED_GLASS_PANE
  nextPage: "&aNext Page"
  previousPage: "&cPrevious Page"
  punishLore:
    - ""
    - " &5● &dSuspected: &f{player}"
    - " &5● &dBanned by: &f{staffer}"
    - " &5● &dReason: &f{reason}"
    - ""
    - " &5● &dType: &7{action}"
    - " &5● &dBanned the: &7{banDate}"
    - " &5● &dExpires: &7{expiration}"